version: "3.7"
services:
  network_info:
    image: network_info
    build:
      context: .
    command: -c postgresql+psycopg://network_info:network_info@db:5432/network_info
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: network_info
      POSTGRES_USER: network_info
      POSTGRES_PASSWORD: network_info
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
